name: Standard workflow
on:
  push:
    branches:    
      - main
  workflow_dispatch:
     inputs:
       addRunId:
         description: 'Add run_id file to cache'
         required: true
         type: boolean
         default: true
#
env:
  cacheName: my-cache
  cacheFile: run.log
#
jobs:
  preparation:
    runs-on: ubuntu-latest
    name: Workflow preparation
    env:
      cacheKey: ${{ format( '**/{0}/{1}', env.cacheName, env.cacheFile ) }}
    steps:
      ## ---------------------------------------------------
      - name: Init Cache
        id: cache
        # src: 
        uses: actions/cache@v3
        with:
          path: ${{ env.cacheName }}
          # Note: The cache is immutable and cannot be updated once created.
          #key: ${{ env.cacheName }}-${{ github.run_id }}
          key: ${{ env.cacheName }}-${{ hashFiles( env.cacheKey ) }}
          restore-keys: |
            ${{ env.cacheName }}
      ## ---------------------------------------------------
      - name: Setup cache
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "cache-hit[${{ steps.cache.outputs.cache-hit }}]"
          if [ ! -e ${{ env.cacheName }} ]; then
            mkdir ${{ env.cacheName }}
          fi
          cd ${{ env.cacheName }}
          echo "addRunId[${{ inputs.addRunId }}]"
          if [ "${{ inputs.addRunId }}" = 'true' ]; then 
            touch ${{ github.run_id }}
          fi
          echo runID:[${{ github.run_id }}][preparation] >> ${{ env.cacheFile }}
      ## ---------------------------------------------------
      - name: Debug
        run: |
          ls -laR
          set
  construction:
    runs-on: ubuntu-latest
    needs: preparation
    name: Artifact construction
    env:
      cacheKey: ${{ format( '**/{0}/{1}', env.cacheName, env.cacheFile ) }}
    steps:
      ## ---------------------------------------------------
      - name: Init Cache
        id: cache
        # src: 
        uses: actions/cache@v3
        with:
          path: ${{ env.cacheName }}
          # Note: The cache is immutable and cannot be updated once created.
          #key: ${{ env.cacheName }}-${{ github.run_id }}
          key: ${{ env.cacheName }}-${{ hashFiles( env.cacheKey ) }}
          restore-keys: |
            ${{ env.cacheName }}
      ## ---------------------------------------------------
      - name: Test cache
        run: |
          echo "addRunId[${{ inputs.addRunId }}]"
          ## 
          cd ${{ env.cacheName }}
          cat ${{ env.cacheFile }}
          ##
      ## ---------------------------------------------------
      - name: Debug
        run: |
          ls -laR
          set
  testing:
    runs-on: ubuntu-latest
    needs: construction
    name: Artifact testing
    env:
      cacheKey: ${{ format( '**/{0}/{1}', env.cacheName, env.cacheFile ) }}
    steps:
      ## ---------------------------------------------------
      - name: Init Cache
        id: cache
        # src: 
        uses: actions/cache@v3
        with:
          path: ${{ env.cacheName }}
          # Note: The cache is immutable and cannot be updated once created.
          #key: ${{ env.cacheName }}-${{ github.run_id }}
          key: ${{ env.cacheName }}-${{ hashFiles( env.cacheKey ) }}
          restore-keys: |
            ${{ env.cacheName }}
      ## ---------------------------------------------------
      - name: Run greeting
        id: hello
        uses: davekpatrick/action-learn-helloworld@main
        with:
          greetingType: 'Hello'
      ## ---------------------------------------------------
      # Use the output from the action
      - name: Print greeting
        run: echo "${{ steps.hello.outputs.greetingMessage }}"
      ## ---------------------------------------------------
      - name: Test cache
        run: |
          echo "addRunId[${{ inputs.addRunId }}]"
          ## 
          cd ${{ env.cacheName }}
          echo runID:[${{ github.run_id }}][testing] >> ${{ env.cacheFile }}
          cat ${{ env.cacheFile }}
          ## 