name: Standard workflow
on:
  push:
    branches:    
      - main
  workflow_dispatch:
     inputs:
       addRunId:
         description: 'Add run_id file to cache'
         required: true
         type: boolean
         default: true
#
env:
  TF_IN_AUTOMATION: true
  TERRAFORM_CODE_PATH: ./terraform
  TERRAFORM_VERSION: 1.3.3
#
jobs:
  preparation:
    runs-on: ubuntu-latest
    name: Workflow preparation
    steps:
      ## ---------------------------------------------------
      - name: Base setup
        id: setup
        run: |
          echo "NOW=$(/bin/date -u "+%Y%m%d%h%m%s")" >> $GITHUB_OUTPUT
      ## ---------------------------------------------------
      - uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Terraform installation
        id: terraform-install
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
      ## ---------------------------------------------------
      - name: Terraform initialization
        id: terraform-init
        run: |
          cd ${{ env.TERRAFORM_CODE_PATH }}
          terraform init
      ## ---------------------------------------------------
      - name: Terraform install validataion
        id: terraform-install-validate
        run: |
          pwd
          find .
          set
          terraform version
      ## ---------------------------------------------------
      - name: Cache setup
        id: cache
        # src: 
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.TERRAFORM_CODE_PATH }}/.terraform
          # Note: The cache is immutable and cannot be updated once created.
          key: ${{ runner.os }}-terraform-providers-${{ github.run_id }}-${{ steps.setup.outputs.NOW }}
          restore-keys: |
            ${{ runner.os }}-terraform-providers-${{ github.run_id }}
            ${{ runner.os }}-terraform-providers
      ## ---------------------------------------------------
      - name: Debug
        run: |
          cd ${{ env.TERRAFORM_CODE_PATH }}
          ls -laR
          set
  construction:
    runs-on: ubuntu-latest
    needs: preparation
    name: Artifact construction
    steps:
      ## ---------------------------------------------------
      - name: Base setup
        id: setup
        run: |
          echo "NOW=$(/bin/date -u "+%Y%m%d%h%m%s")" >> $GITHUB_OUTPUT
      ## ---------------------------------------------------
      - uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Cache setup
        id: cache
        # src: 
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.TERRAFORM_CODE_PATH }}/.terraform
          # Note: The cache is immutable and cannot be updated once created.
          key: ${{ runner.os }}-terraform-providers-${{ github.run_id }}-${{ steps.setup.outputs.NOW }}
          restore-keys: |
            ${{ runner.os }}-terraform-providers-${{ github.run_id }}
            ${{ runner.os }}-terraform-providers
      ## ---------------------------------------------------
      - name: Test cache
        run: |
          cd ${{ env.TERRAFORM_CODE_PATH }}
          ls -laR
  testing:
    runs-on: ubuntu-latest
    needs: construction
    name: Artifact testing
    steps:
      ## ---------------------------------------------------
      - name: Base setup
        id: setup
        run: |
          echo "NOW=$(/bin/date -u "+%Y%m%d%h%m%s")" >> $GITHUB_OUTPUT
      ## ---------------------------------------------------
      - uses: actions/checkout@v3
      ## ---------------------------------------------------
      - name: Cache setup
        id: cache
        # src: 
        uses: actions/cache@v3
        with:
          path: |
            ${{ env.TERRAFORM_CODE_PATH }}/.terraform
          # Note: The cache is immutable and cannot be updated once created.
          key: ${{ runner.os }}-terraform-providers-${{ github.run_id }}-${{ steps.setup.outputs.NOW }}
          restore-keys: |
            ${{ runner.os }}-terraform-providers-${{ github.run_id }}
            ${{ runner.os }}-terraform-providers
      ## ---------------------------------------------------
      - name: Test cache
        run: |
          cd ${{ env.TERRAFORM_CODE_PATH }}
          ls -laR
      ## ---------------------------------------------------
      - name: Run greeting
        id: hello
        uses: davekpatrick/action-learn-helloworld@main
        with:
          greetingType: 'Hello'
      ## ---------------------------------------------------
      # Use the output from the action
      - name: Print greeting
        run: echo "${{ steps.hello.outputs.greetingMessage }}"