on:
  push:
    branches:    
      - main
  workflow_dispatch:
     inputs:
       addRunId:
         description: 'Add run_id file to cache'
         required: true
         type: boolean
         default: true

env:
  cacheName: my-cache

jobs:
  helloWorld:
    runs-on: ubuntu-latest
    name: Run Greeting
    steps:
      ## ---------------------------------------------------
      - name: Init Cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.cacheName }}
          key: ${{ env.cacheName }}-${{ github.run_id }}
          restore-keys: |
            ${{ env.cacheName }}
      ## ---------------------------------------------------
      - name: Setup cahce
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          if [ ! -e ${{ env.cacheName }} ]; then
            mkdir ${{ env.cacheName }}
          fi
          cd ${{ env.cacheName }}
          echo "addRunId[${{ inputs.addRunId }}]"
          if [ "${{ inputs.addRunId }}" = "true" ]; then 
            touch ${{ github.run_id }}
          fi
          ls -la
      ## ---------------------------------------------------
      - name: Run greeting
        id: hello
        uses: davekpatrick/action-learn-helloworld@main
        with:
          greetingType: 'Hello'
      # Use the output from the action
      - name: Print greeting
        run: echo "${{ steps.hello.outputs.greetingMessage }}"